// <auto-generated />
using Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Models.Organisation", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationId");

                    b.ToTable("organisations");

                    b.HasData(
                        new
                        {
                            OrganisationId = 1,
                            OrganisationName = "Org1"
                        },
                        new
                        {
                            OrganisationId = 2,
                            OrganisationName = "Org2"
                        },
                        new
                        {
                            OrganisationId = 3,
                            OrganisationName = "Org3"
                        },
                        new
                        {
                            OrganisationId = 4,
                            OrganisationName = "Org4"
                        },
                        new
                        {
                            OrganisationId = 5,
                            OrganisationName = "Org5"
                        },
                        new
                        {
                            OrganisationId = 6,
                            OrganisationName = "Org6"
                        },
                        new
                        {
                            OrganisationId = 7,
                            OrganisationName = "Org7"
                        },
                        new
                        {
                            OrganisationId = 8,
                            OrganisationName = "Org8"
                        },
                        new
                        {
                            OrganisationId = 9,
                            OrganisationName = "Org9"
                        },
                        new
                        {
                            OrganisationId = 10,
                            OrganisationName = "Org10"
                        },
                        new
                        {
                            OrganisationId = 11,
                            OrganisationName = "Org11"
                        },
                        new
                        {
                            OrganisationId = 12,
                            OrganisationName = "Org12"
                        },
                        new
                        {
                            OrganisationId = 13,
                            OrganisationName = "Org13"
                        },
                        new
                        {
                            OrganisationId = 14,
                            OrganisationName = "Org14"
                        },
                        new
                        {
                            OrganisationId = 15,
                            OrganisationName = "Org15"
                        },
                        new
                        {
                            OrganisationId = 16,
                            OrganisationName = "Org16"
                        },
                        new
                        {
                            OrganisationId = 17,
                            OrganisationName = "Org17"
                        },
                        new
                        {
                            OrganisationId = 18,
                            OrganisationName = "Org18"
                        },
                        new
                        {
                            OrganisationId = 19,
                            OrganisationName = "Org19"
                        },
                        new
                        {
                            OrganisationId = 20,
                            OrganisationName = "Org20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
